# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'TableView' do
  use_frameworks!

  # Pods for TableView
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'FirebaseFirestoreSwift'
  pod 'CLTypingLabel', '~> 0.4.0'

end
